### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by marcuspoehls** [salzhrani/hapi-brute#1]
Hi Samy,

is this plugin production-ready? Actually, I would love to use it for a project and accessable via NPM. Do you have any plans to publish an official release?

Thanks for your work!

**Comment by salzhrani** [comment]
I am holding on publishing or at least stamping it as production ready until someone gives it a look and tries it out. I can publish it if your prefer but I am not certain of its readiness for production.

**Comment by salzhrani** [comment]
The module is published to npm
